
geofence: '../data/nyc_geofence.geojson'

demand:
  data_file: '../data/rides.feather'

fleet:
  stations: '../data/nyc_bus_stops.geojson'
  vehicles: 10
  router: 'linear'
  # router: 'osrm'

bookings:
  # in minutes
  max_pending_time: 2
  bookings_per_hour: 50

simulation:
  # in minutes
  duration: 120
  starting_time: '2015-02-01 12:00:00'
  resolution: 7
  # map match pickups and dropoffs
  # map_match: True
  map_match: False

  demand_seed: 123123
  fleet_seed: 11
  # in seconds
  clock_step: 10

  output: 'simulation_output_example.csv'

solvers:
  greedy_matcher:
    # radius in minutes
    search_radius: 5
    router: 'linear'
    # router: 'osrm'

routers:
  osrm:
    server: 'http://localhost:5010'
  linear:
    speed: 20